image: gitpod/workspace-ruby-2:2023-02-27-14-14-03

tasks:
  - name: initialize docker
    init: docker compose pull

  - name: ruby backend
    command: cd src && bundle exec ruby app.rb

ports:
  - port: 4567
    onOpen: ignore

vscode:
  extensions:
    - Shopify.ruby-lsp
    - janisdd.vscode-edit-csv
    - dracula-theme.theme-dracula