tasks:
  - name: docker backend
    init: docker compose pull

  - name: ruby backend
    before: |
      rvm install openssl
      rvm reinstall 2.7.0 --with-openssl-dir=/home/$(whoami)/.rvm/usr
      rvm use ruby-2.7.0
    init: |
      cd src && bundle install
    command: bundle exec ruby app.rb

ports:
  - port: 4567
    onOpen: ignore

vscode:
  extensions:
    - Shopify.ruby-lsp
    - ms-azurertools.vscode-docker
    - janisdd.vscode-edit-csv
    - dracula-theme.theme-dracula