# Gemfile
source 'https://rubygems.org'

# Add your project dependencies here
# Example: gem 'sinatra'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'csv'
gem 'net'
gem 'uri'
gem 'rswag-ui'
gem 'rswag-api'
gem 'rswag-specs'

# Specify the Ruby version
ruby '2.7.6'
